### ISSUE TITLE
Update roadmap

### ISSUE THREAD

**Issue by llrs** [ropensci/rtweet#471]
Roadmap to update rtweet and clean up issues and PR listed below (on date 2021/02/15):
 - Label/Classify them
 - Close duplicates, or non reproducible if the author do not reply in 1 month.
 - Fix errors/bugs
 - Implement enhancements
 - ? CRAN release? Date:?

<details>
<summary>Code to  return this list of issues/PR (ID, title, comments, last update date) :</summary>
```r
library("tidyverse")
remotes::install_github("llrs/socialGH")
socialGH::get_issues("ropensci/rtweet") %>% 
  filter(state != "closed") %>% 
  arrange(id) %>% 
  mutate(fix = " - [ ]") %>% 
  select(fix, id, title, n_comments, updated) %>% 
  knitr::kable() %>% 
  gsub("\\|", ",", .) %>% 
  gsub("^,\\s*", "", .) %>% 
  gsub(",\\s*$", "", .) %>% 
  gsub(",\\s*", ", ", .) %>% 
  gsub("\\s*,", ",", .) %>% 
  gsub("\\], ", "] #", .) %>% 
  # gsub("\\] ([0-9]+)", "] #\\2", .) %>% 
  cat(file = "status.txt", sep = "\n")
```

</details>

- [ ] #41, Need basic description of common data structures, 3, 2016-11-29 00:15:30 
- [ ] #88, Remove tryCatch, 1, 2017-06-07 03:57:36 
- [ ] #120, Mentions of deleted accounts cause confusion in tweets data, 2, 2017-10-09 01:49:10 
- [ ] #138, Feature request: add function for "GET friendships/show", 3, 2017-11-20 21:30:47 
- [x] #141, Invalid or expired token., 3, 2018-03-03 18:05:36 
- [x] #156, Authorize on AWS Ubuntu Server, 11, 2018-06-18 08:11:03 
- [x] #161, instructions for development/test setup / tokens, 2, 2018-01-07 18:11:26 
- [ ] #164, `get_thread()` useful?, 6, 2018-02-08 01:07:52 
- [ ] #173, Feature request: global retryonratelimit, 2, 2018-02-08 10:13:35 
- [x] #176, FeatureRequest: Full Archive Search Accesibility, 14, 2020-01-27 17:20:44 
- [x] #182, curls & retryonlimit issue, 6, 2018-05-09 17:40:13 
- [ ] #184, Allow stream parsing of non-rtweet, historical json tweet objects?, 0, 2018-02-20 16:46:34 
- [x] #186, image captions, 1, 2018-02-22 21:07:55 
- [ ] #188, Modification of profile / profile pic, 1, 2018-03-24 16:14:47 
- [x] #251, Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission, :    Forbidden (HTTP 403)., 30, 2020-10-03 23:35:36 
- [x] #258, Error in init_oauth1.0(self$endpoint, self$app, permission = self$params$permission, :    Forbidden (HTTP 403). In addition: Warning message: In strptime(x, fmt, tz = "GMT") :   unknown timezone 'default/America/New_York', 1, 2018-06-20 15:07:35 
- [x] #261, error with lookup_coords, 22, 2020-08-20 18:29:51 
- [x] #262, rtweet 0.6.4, 1, 2018-06-21 14:14:11 
- [x] #263, stream_tweets() stops collecting before the declared timeout, 3, 2018-07-23 08:31:01 
- [x] #264, creating token,, 1, 2018-06-30 12:57:20 
- [x] #265, Forbidden (HTTP 403) Error, 3, 2019-02-16 11:21:55 
- [x] #266, 0.6.7 get_timeline: rate limit error, 7, 2019-10-01 15:13:22 
- [x] #267, Parse_stream results in empty object (NULL) with .json file, 0, 2018-07-03 15:04:09 
- [x] #270, Stream  tweet directly into database, 1, 2020-10-14 19:21:04 
- [x] #273, Same function - two outputs! #lookup_users act differently - Why?, 0, 2018-07-14 17:42:12 
- [x] #274, get_timelines for tweet keywords or hashtags, 5, 2019-12-14 13:59:24 
- [x] #277, Invalid 'time' error with using get_friends(), 3, 2020-08-24 03:25:49 
- [ ] #279, Feature suggestion: include a dataset with some tweet IDs, 0, 2018-08-12 11:44:33 
- [x] #281, Issue with selection of tweets, 5, 2018-10-02 19:17:59 
- [x] #283, Error in create_token() due unused argument (acess_token), 4, 2018-11-23 22:08:09 
- [x] #284, Error in get_followers for large amounts of followers, 0, 2018-08-20 21:01:41 
- [ ] #287, Is possible search a tweet by the source?, 0, 2018-08-29 15:02:03 
- [x] #288, Using get_friends for a large number of users, 1, 2019-11-15 15:24:09 
- [ ] #289, How I can get location(from user profile) and geo location of tweet?Interested specifically on South Africa users.I have tried using lookupcoords( ) function but I still get below error:Error in search_tweets("lang:es", geocode = Southafrica_coord, n = 20) :    object 'Southafrica_coord' not found, 1, 2018-09-22 21:29:12 
- [x] #292, search_users with parse=TRUE fails if all found users haven't tweeted anything, 0, 2018-09-25 18:06:06 
- [x] #294, stream_tweets2() does not save the output, 10, 2020-06-17 08:15:58 
- [x] #295, could not find function "clean_tweets", 0, 2018-10-14 13:19:15 
- [ ] #296, Stream tweets by long-lat seems inaccurate, 0, 2018-10-16 01:31:22 
- [x] #297, get_followers() returns empty, 1, 2019-08-05 05:55:21 
- [ ] #298, Request: Scheduled Tweets?, 0, 2018-10-26 14:59:00 
- [ ] #300, plain_tweets returns the same text, 0, 2018-11-16 17:51:29 
- [x] #301, Video upload via rtweet, 4, 2019-02-03 05:12:28 
- [x] #303, Problems with UTF8 on Mac OS X Mojave, 1, 2019-02-19 10:04:38 
- [x] #304, Problem Lookup_users function, 0, 2019-01-07 12:38:40 
- [ ] #305, add functions for tweet embedding and threading, 1, 2019-01-31 14:15:10 
- [ ] #308, get_friends / get_follows consistency, 0, 2019-01-30 18:40:33 
- [x] #309, replies from API not threaded, 1, 2019-02-01 12:52:36 
- [x] #314, Waiting about 71 minutes, 1, 2019-02-18 20:38:48 
- [x] #315, Add a twitter markdown embed output, 1, 2019-02-21 21:34:20 
- [x] #317, compatibility with twitter premium API: make tweets per requests dynamic?, 10, 2020-04-22 09:42:21 
- [x] #318, next_cursor overflow in get_friends, 1, 2019-03-07 07:17:12 
- [ ] #320, Not Retrieving All of a User's Timeline When Under 3200 Tweets, 2, 2020-01-12 11:19:41 
- [x] #321, Warning: 215 - Bad Authentication data., 0, 2019-03-15 11:54:48 
- [x] #322, Geo Location  and coordinates format, 5, 2019-04-11 11:40:06 
- [ ] #325, Error in lookup_users > users_with_tweets, 5, 2021-02-15 19:38:26 
- [x] #326, Dowload more than 18, 000 tweets per request, 1, 2019-04-18 07:18:39 
- [x] #327, Using rtweet on rstudio.cloud, 2, 2019-07-15 14:37:54 
- [x] #328, search_fullarchive token, 1, 2019-08-14 13:58:55 
- [x] #329, Short Tweet statuses blocked by error 'cannot exceed 280 characters', 9, 2019-10-28 15:53:14 
- [ ] #330, Fixing Inversion in tweet length allowed limit., 1, 2019-09-12 14:46:25 
- [ ] #333, Error in attr(rt, "users") <- users : attempt to set an attribute on NULL, 1, 2020-02-11 18:10:59 
- [ ] #334, search_tweets() provides a warning if the token is invalid or expired but lookup_statuses() does not, 0, 2019-06-09 18:43:52 
- [x] #335, documentation grammar, 0, 2019-06-17 22:20:34 
- [x] #338, Export `home_user()`, 0, 2019-07-05 14:49:44 
- [ ] #339, get_friends() should return a 0 x 2 tibble on failure, 2, 2020-09-07 02:56:51 
- [ ] #341, Deal more gracefully with protected users, 0, 2019-06-30 17:31:23 
- [ ] #342, Multiple tokens, 7, 2020-01-25 20:06:40 
- [ ] #343, CSV export and open in Excel, 1, 2019-07-20 09:41:17 
- [x] #344, Importing bookmarked tweets, 1, 2019-07-20 09:27:48 
- [x] #345, Not able to install the package, 3, 2019-08-03 19:19:07 
- [ ] #346, search_tweets with retryonratelimit = TRUE goes beyond requested limit, 2, 2019-10-20 23:48:01 
- [x] #347, search_fullarchive issues multiple requests for one individual request, 17, 2020-08-21 13:18:45 
- [ ] #348, stream_tweets does not filter by language, 4, 2020-03-05 14:33:54 
- [ ] #350, Problem with streaming connection, 2, 2020-09-01 20:08:17 
- [ ] #351, Problem with ts_plot timezone, 1, 2019-09-05 10:32:17 
- [x] #352, Preferred method for exiting stream_tweets(...timeout=Inf)?, 0, 2019-10-02 06:57:33 
- [x] #353, Created only about 15 tweets rate limited, created 25 tweets and suspended, 0, 2019-09-15 21:31:47 
- [x] #354, Data lost after stream_tweets()/stream_tweets2() finishes, 4, 2020-09-30 02:16:10 
- [ ] #355, Premature EOF when parsing, 4, 2019-09-26 14:06:59 
- [ ] #356, parse_stream error v0.6.7 vs 0.6.9, 10, 2019-10-03 21:26:28 
- [ ] #358, Sandbox feature Issues, 0, 2019-09-30 16:57:01 
- [x] #359, search_fullarchive setup issue, 12, 2020-03-03 00:51:50 
- [x] #360, Parse rds files from search_fullarchive, 0, 2019-10-15 21:27:50 
- [ ] #362, lists_statuses() returns truncated tweets, 2, 2019-12-20 12:08:02 
- [ ] #363, Collecting replies to a tweet, 3, 2020-07-31 15:33:09 
- [ ] #365, Implement alternative geocoder, 0, 2019-11-01 07:57:16 
- [x] #368, Add retryonratelimit for premium search_fullarchive searches, 23, 2021-02-15 19:34:20 
- [ ] #369, Accessing `counts` endpoint, 6, 2020-02-18 21:40:36 
- [ ] #374, Adding the collapse delimiter as parameter, 1, 2019-12-19 18:36:12 
- [ ] #375, Fix Twitter Premium API Max Requests in search_tweets.R, 1, 2020-02-20 16:41:00 
- [ ] #378, fix truncated tweet text in lists_statuses, 0, 2019-12-20 12:06:59 
- [ ] #379, stream_tweets(): redirect data stream to standard output, 0, 2019-12-31 04:33:36 
- [ ] #380, Invalid Path on Windows for set_renv (via create_token), 0, 2020-01-12 16:02:57 
- [ ] #381, Properly save TWITTER_PAT path on Windows., 0, 2020-01-12 16:52:00 
- [ ] #382, get_timeline doesn't retrieve 3200 tweets for realDonaldTrump, 0, 2020-01-13 12:27:15 
- [x] #383, maxResults parameter in rtweets set to 100 default, 3, 2020-04-19 20:46:15 
- [ ] #384, Next_Cursor Doesn’t work with Direct_message, 0, 2020-01-19 07:02:52 
- [x] #385, Define isFALSE if not available in base, 0, 2020-01-30 08:02:20 
- [ ] #387, Confusion about bearer tokens, 1, 2020-02-14 14:24:16 
- [ ] #388, Recovering tweet contents from temp files after using `search_30day()`, 1, 2020-02-24 14:47:21 
- [ ] #389, rm rOpenSci mention in DESCRIPTION, 0, 2020-02-06 12:47:00 
- [x] #390, search_tweets() Error in vector("list", ntimes) : invalid 'length' argument, 3, 2020-02-05 19:29:38 
- [ ] #391, lookup_coords does not work even if I enter Google API, 1, 2020-02-06 21:03:59 
- [ ] #392, Tweets with media do not show their media_url, 1, 2020-02-10 15:53:58 
- [x] #394, Authentication problems with premium account, 5, 2020-05-18 09:13:05 
- [ ] #396, Invalid time error using get_followers, 0, 2020-03-08 15:03:52 
- [x] #397, Error in curl::curl_fetch_memory(url, handle = handle): Timeout was reached, 13, 2020-08-13 17:24:53 
- [ ] #398, Scraping tweets from a specific user in a specific timeframe., 0, 2020-03-13 17:36:26 
- [x] #399, Enable support for chunked media endpoint (mp4 file support), 1, 2020-03-14 16:10:28 
- [x] #400, Error in curl::curl_fetch_memory(url, handle = handle): gnutls_handshake() failed: An unexpected TLS packet was received., 1, 2020-03-15 12:11:44 
- [x] #401, search_tweets issue with retryonratelimit, 4, 2020-05-31 22:19:08 
- [x] #402, Twitter Developer Labs data and formats, 0, 2020-03-19 17:45:13 
- [x] #403, This site can it be reached, 0, 2020-03-19 18:20:49 
- [x] #404, Cannot stream tweets, 3, 2020-12-22 12:10:13 
- [x] #405, this site can't be reached - 127.0.0.1 refused to connect., 1, 2020-04-01 03:37:06 
- [x] #407, Error while using browser based authentication from online shiny App, 1, 2020-08-05 16:58:30 
- [x] #410, Error in authentication token, 3, 2020-05-14 20:38:01 
- [ ] #411, rate_limit() not updating, 4, 2020-11-22 22:59:19 
- [ ] #412, Search Tweets: not all hashtags and mentions are extracted, 1, 2020-04-28 19:09:19 
- [x] #413, cannot open compressed file '/Users/xx.rds', probable reason 'Permission denied, 3, 2020-05-09 11:06:19 
- [ ] #415, Accessing Data through Premium API, 0, 2020-04-28 17:50:59 
- [x] #416, Error: API did not return json, 0, 2020-05-01 12:25:19 
- [ ] #417, fix parsing of path to token during auto-auth, 1, 2020-05-05 14:13:02 
- [ ] #418, get_timeline() returns "Error: API did not return json", 27, 2020-11-25 00:16:29 
- [x] #419, Iterate backwards: "get_timeline", 1, 2020-05-12 19:10:57 
- [ ] #420, Update rtweet-package.R, 0, 2020-05-13 16:28:22 
- [x] #421, Authentication issue: Error in file(con, "w") : cannot open the connection, 0, 2020-05-14 23:23:13 
- [ ] #422, fixes reference to old and missing vignette in `get_token`, `get_tokens`, 0, 2020-05-15 01:18:54 
- [x] #423, Error in curl_fetch_memory schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326), 0, 2020-05-15 04:37:56 
- [x] #424, Cannot open the connection and cannot open file ".Renviron", 1, 2020-12-22 12:29:31 
- [ ] #425, Added alt-text support, 2, 2021-02-06 21:10:29 
- [ ] #426, retweet with a comment, 2, 2020-07-30 08:38:30 
- [x] #427, search_tweets returning duplicates, 0, 2020-06-09 20:41:05 
- [x] #429, Search_fullarchive stopped getting Premium tweets after 10 requests, 0, 2020-06-14 17:05:45 
- [ ] #430, Language argument "lang=" doesn't seem to work with get_timelines, 0, 2020-06-20 11:28:07 
- [x] #431, search_user and search_tweet have identical results and structure, 1, 2020-07-30 08:35:46 
- [x] #433, get_timelines Error: API did not return json, 1, 2020-07-31 21:36:39 
- [ ] #435, rtweet.info is down, 4, 2020-11-18 18:46:51 
- [ ] #436, lookup_friendships stops collecting info, 3, 2020-07-31 16:48:37 
- [ ] #437, Sandbox: use of search_30day & search_fullarchive, 2, 2020-11-30 17:52:33 
- [ ] #438, rtweet authentication not working for script running as a local job, 0, 2020-08-11 18:19:45 
- [x] #439, 'Could not authenticate you' when using search_tweets function, 0, 2020-08-13 15:23:29 
- [x] #440, Error in curl::curl_fetch_memory(url, handle = handle) : Failed to connect to api.twitter.com port 443: Timed out, 0, 2020-08-14 03:39:03 
- [ ] #441, Search_fullarchive doesn't support query longer than 500 characters, 2, 2020-12-25 19:04:27 
- [ ] #442, The search_tweets function does not retrieve the number of tweets set in "n =" argument., 4, 2020-09-18 19:40:17 
- [ ] #443, get_friends() fails for all user_ids if any one user_id is protected/missing/etc., 3, 2021-01-13 14:32:15 
- [x] #444, I want to search tweets of a specific list, I was able to, but now I can't. has the instructions changed?, 1, 2020-12-22 12:27:13 
- [ ] #445, Use of V2 API, 2, 2020-09-12 02:44:17 
- [x] #446, get_timelines broken, 3, 2020-09-21 06:51:15 
- [x] #447, Wildcards, 4, 2020-09-30 13:57:25 
- [ ] #448, get_my_timeline displays incorrect created_at date, 0, 2020-10-01 18:12:25 
- [ ] #449, search_tweets pulls way more tweets than n specified, 2, 2020-10-26 20:46:25 
- [x] #450, Error: API did not return json (please help), 3, 2020-10-27 00:44:11 
- [ ] #451, post_message() not attaching media, 0, 2020-10-17 22:44:27 
- [ ] #452, Provide a function to parse the response of post_tweet for easy creation of threads., 0, 2020-10-20 09:16:43 
- [x] #453, Language filter not working on stream_tweets, 0, 2020-10-20 19:28:24 
- [ ] #454, minor spelling fix to post_tweet man, 0, 2020-10-25 03:31:22 
- [x] #456, Unnecessary "Requesting token on behalf of user...", 1, 2020-12-22 12:05:26 
- [ ] #458, Tweetshot risks being obsoleted by Twitter December 2020, 3, 2021-01-11 13:55:50 
- [ ] #459, lists_statuses() does not return tweet photo info if there are multiple photos, 0, 2020-12-06 15:37:47 
- [x] #460, post_tweet hangs when posting media, 2, 2021-01-05 16:28:00 
- [x] #461, filter get_timelines for special keywords, 1, 2020-12-24 15:01:37 
- [x] #462, get_timeline() retryonratelimit = T not working for me, 6, 2021-01-10 10:00:24 
- [ ] #467, Unmute, 0, 2021-02-15 19:34:04 
- [ ] #468, Support for Academic Product Track?, 6, 2021-02-15 19:34:04 
- [ ] #469, Support multiple tokens, 0, 2021-02-15 19:34:05 
- [ ] #470, Raise error on unsupported parameters, 0, 2021-02-15 19:34:34

**Comment by llrs** [comment]
First batch (ending on issue 317): 33/50 were closed

<details>
<summary>Number of issues of the list, issue number</summary>

50: issue 317
100: issue 388
150: issue 447
</details>

**Comment by llrs** [comment]
Second batch: total 53 closed /100 reviewed from last 50 only 20 issues were closed

At least 3 question about authentication on servers (workaround copy token created in local computer)
Also many questions about location and coordinates.
There were many PR that I didn't close/merge. 
Also there seems to be many helper functions that do nothing:

```r
A <- function(x, y, z) {
do.all(A_, list(x = x, y = y, z = z)
}

A_ <- function(x, y, z) {
# Lots of stuff
}
```

This could be updated to 

```r
A <- function(x, y, z) {
# Do stuff
}
```

This would be slightly faster and wouldn't pollute the namespace so much. 

Also it seems that the package assumes that only one token is in use. As an issue mentions support for multiple tokens would be great. This would solve problems with bearer tokens and others.

**Comment by llrs** [comment]
Update 79/167 so 79/150 reviewed, from the last 50 26 were closed.
This was faster as many are better reported or I was already commenting on the issues.

**Comment by llrs** [comment]
Finishing reviewing them 85/167 closed, so half of the issues remain.

**Comment by llrs** [comment]
Following some discussions next release will have breaking changes and thus be major version change?

1) Tokens: change the default provided by rtweet, and where and how to store them.
2) Tests: Make test more consistent and easier to work with (probably solving 1 will also help) and using vcr will help prevent changing responses.
3) Improve internal functions: Stop using as examples internals functions, simplify the process
4) Provide more functionality: mute/unmute, list those muted, API v2, academic research product...
5) Remove non-core functionality: ts_plot?

**Comment by llrs** [comment]
Note to self, document that multiple images and multiple alt text work, but multiple images and 1 alt_text doesn't. `post_tweet("status", media = c("image1.png", "image2.png"), media_alt_text = c("alt_text1"))`, also test that formally on its own file.

**Comment by llrs** [comment]
Seems that this is no longer the plan
